after-login-command = []
after-startup-command = []
# start-at-login = false
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
# automatically-unhide-macos-hidden-apps = false
automatically-unhide-macos-hidden-apps = true
[key-mapping]
preset = 'qwerty'
[gaps]
inner.horizontal = 0
inner.vertical = 0
outer.left = 0
outer.bottom = 0
outer.top = 0
outer.right = 0
[mode.main.binding]
cmd-enter = ['exec-and-forget open /Applications/Ghostty.app', 'workspace 2:âš™ï¸']
ctrl-alt-left = 'move left'
ctrl-alt-down = 'move down'
ctrl-alt-up = 'move up'
ctrl-alt-right = 'move right'
alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'
alt-1 = 'workspace 1:ğŸ‘¨â€ğŸ’»'
alt-2 = 'workspace 2:âš™ï¸'
alt-3 = 'workspace 3:ğŸ› ï¸'
alt-4 = 'workspace 4:ğŸ“'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8:ğŸ¶'
alt-9 = 'workspace 9:ğŸ’¬'
alt-0 = 'balance-sizes'
alt-shift-1 = 'move-node-to-workspace 1:ğŸ‘¨â€ğŸ’»'
alt-shift-2 = 'move-node-to-workspace 2:âš™ï¸'
alt-shift-3 = 'move-node-to-workspace 3:ğŸ› ï¸'
alt-shift-4 = 'move-node-to-workspace 4:ğŸ“'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8:ğŸ¶'
alt-shift-9 = 'move-node-to-workspace 9:ğŸ’¬'
alt-tab = 'workspace-back-and-forth'
# osascript -e 'id of app "App Name"'
[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace 1:ğŸ‘¨â€ğŸ’»'
[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
run = 'move-node-to-workspace 1:ğŸ‘¨â€ğŸ’»'
[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = 'move-node-to-workspace 1:ğŸ‘¨â€ğŸ’»'
[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = 'move-node-to-workspace 2:âš™ï¸'
[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = 'move-node-to-workspace 3:ğŸ› ï¸'
[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij'
run = 'move-node-to-workspace 3:ğŸ› ï¸'
[[on-window-detected]]
if.app-id = 'md.obsidian'
run = 'move-node-to-workspace 4:ğŸ“'
[[on-window-detected]]
if.app-id = 'com.tidal.desktop'
run = 'move-node-to-workspace 8:ğŸ¶'
[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace 9:ğŸ’¬'
